### ISSUE TITLE
Mosco V140b2 process shows high CPU performance load during compile/deploy time

### ISSUE THREAD

**Issue by Rollo62b** [DelphiWorlds/Mosco#10]
Hi Dave,

thanks for the nice tools you provide, makes live easier.

When using within a small and normal Macos Ventura VM ( 2 cores, 4GB ) under Parallels, I noticed that the total processes might occupy 100% CPU.
When closing Mosco and using PAServer alone, CPU usage stay perfectly below 100%.
Why does Mosco eating so much ressources when compiling/deploying, while only PAServer should do the work ?
Maybe this is some issue in V140b2 only, I hope you can fix it in the release.

**Comment by DelphiWorlds** [comment]
> while only PAServer should do the work ?

I can still have a look at the CPU usage, however Mosco does not interact with PAServer - it executes all commands on its own.

**Comment by Rollo62b** [comment]
Just to give an impression:
This is idle, with PAServer running, no Mosco running
![grafik](https://user-images.githubusercontent.com/4697968/215147536-86963dce-fe0f-4a82-89bd-836f8e6e552c.png)

This is idle then deployment, with PAServer alone ( the heavy load start when RadStudio starts "Deplyoment" phase ),
but the whole load stays well in acceptable limits.
![grafik](https://user-images.githubusercontent.com/4697968/215147611-8821814e-b31f-4785-9db3-ca642f7d0f0f.png)

When Mosco is running, the idle load is already much higher ( see around the middle of the core bargraph).
When deplyoment starts, Mosco, PAServer and other tasks adding much load.
![grafik](https://user-images.githubusercontent.com/4697968/215147922-39cec7c1-12ef-4dbf-921a-09c06b168d73.png)

It seems Mosco is doing something in the background, maybe some polling threads or the like,
which can eat up quite a lot of load.

Maybe that helps to better understand the issue.




#

**Comment by DelphiWorlds** [comment]
Pushed an installer for [beta 3](https://github.com/DelphiWorlds/Mosco/tree/master/Beta) that should fix the issue
