### ISSUE TITLE
Error in notarytool submit

### ISSUE THREAD

**Issue by Spelt** [DelphiWorlds/Mosco#11]
Hi,

Thanks for the great work. 

Got an error with the notarization of a pkg with Mosco. The log is below.  It seems that the teamId is not parsed correctly. Maybe it's a good idea just to add the teamId just as an extra parameter in the UI. The teamId should be FZRAYS6xxx

2023/04/12 17:18:31.246 Executing: /usr/bin/pkgbuild --root "/Users/activetickets/PAServer/scratch-dir/Jenkins-MacMini/Boxoffice.app" --install-location "/Applications/Boxoffice.app" --identifier "Boxoffice" --version "3.2.10" "/Users/activetickets/Desktop/Boxoffice.pkg"
2023/04/12 17:18:34.440 Executing: /usr/bin/codesign --sign "Developer ID Installer: Cramgo BV (FZRAYS6xxx)" "/Users/activetickets/Desktop/Boxoffice.pkg" "/Users/activetickets/Desktop/BoxofficeSigned.pkg"
2023/04/12 17:18:34.841 Executing: /usr/bin/xcrun notarytool submit --apple-id "espelt@cramgo.nl" --password "*******************" --team-id "CramgoBV" --no-progress "/Users/activetickets/Desktop/Boxoffice.pkg"
2023/04/12 17:18:35.859 Notarize failed with exit code: 1 - Error: HTTP status code: 403. Invalid or inaccessible developer team ID for the provided Apple ID. Ensure the Team ID is correct and that you are a member of that team.

Sincerely,
Edward

**Comment by DelphiWorlds** [comment]
When Mosco shows the installer creation dialog, in the messages window, it should show the command it executes when retrieving the team ids, like this:

`/usr/bin/xcrun altool --list-providers --username "davidn@radsoft.com.au" --password "*******************"`

Can you run this command in a terminal window (putting your password in the right place), and reply with the output? (OK to obscure part of the team id). I expect you are right that the Mosco code does not parse the results correctly.

**Comment by Spelt** [comment]
Hi

That would be:


ProviderName ProviderShortname PublicID                             WWDRTeamID 
------------ ----------------- ------------------------------------ ---------- 
Cramgo BV    CramgoBV          69a6de79-6de5-aaaa-e053-5b8c7c11a4d1 XXXXXXX

**Comment by DelphiWorlds** [comment]
Ah.. ok. I had assumed that it needs to use the ProviderShortname value when it appears it needs to use the WWDRTeamID value (both of these are the same value, in my case). I'll update Mosco soon to correct for it

**Comment by Spelt** [comment]
Thanks!

**Comment by DelphiWorlds** [comment]
I've pushed v1.4.1 which should fix your issue.

**EDIT** There was an issue that slipped past, which was in the original v1.4.1 installer. If you used this one, please download the updated installer and re-install.

**Comment by Spelt** [comment]
Yes that works

Thanks!
