### ISSUE TITLE
App not starting

### ISSUE THREAD

**Issue by birbilis** [DelphiWorlds/Mosco#6]
After installing the PKG, I launch the app from the Applications by double-clicking on it and it just does nothing (only stays on the Dock, no icon on the Mac menu)

![image](https://user-images.githubusercontent.com/3461504/170963995-086a4623-ea07-4b18-8c5c-b0a380743942.png)

![image](https://user-images.githubusercontent.com/3461504/170963551-00f745c5-6583-45e4-a029-e59d16eace0a.png)

![image](https://user-images.githubusercontent.com/3461504/170963709-d504c9b4-2667-4e43-93ae-12f8f3c81d23.png)

![image](https://user-images.githubusercontent.com/3461504/170963463-36ca0a07-0485-4e0a-8230-202bb5a87b1d.png)

**Comment by DelphiWorlds** [comment]
Please refer to the readme: https://github.com/DelphiWorlds/Mosco/blob/master/README.md
"When Mosco starts, an icon appears in the macOS system bar. Click the icon to access the menu"

**Comment by DelphiWorlds** [comment]
Can you run Mosco from the command line? To do this, run the Terminal app in /Applications/Utilities, then execute this command:

/Applications/Mosco.app/Contents/MacOS/Mosco

You should see lines like this:

```
2022-05-30 21:35:58.549 Mosco[31045:3132129] DEBUG: Mosco 1.2.2
2022-05-30 21:35:58.558 Mosco[31045:3132165] DEBUG: Broker is active at tcp://*:8088
2022-05-30 21:35:58.563 Mosco[31045:3132166] DEBUG: Connecting to broker at tcp://localhost:8088
2022-05-30 21:35:58.564 Mosco[31045:3132166] DEBUG: Connected to broker at tcp://localhost:8088
```
etc

**Comment by birbilis** [comment]
I don't see any icon, in fact it was keeping the app icon in the dock only (no icon or menu in Mac menu bar) and had to tell it to Remove from Dock (guess that was closing it? it was showing a dot underneath the icon on the Dock so I guess it was running [but still not icon on menu]). Had tried that 2-3 times with same effect

now that I run it again it just closes and if I run from the terminal I get:

> The default interactive shell is now zsh.
> To update your account to use zsh, please run `chsh -s /bin/zsh`.
> For more details, please visit https://support.apple.com/kb/HT208050.
> administrators-Mac-mini:~ administrator$ /Applications/Mosco.app/Contents/MacOS/Mosco
> 2022-05-30 20:02:20.774 Mosco[84357:23256409] DEBUG: Mosco 1.2.2
> 2022-05-30 20:02:20.801 Mosco[84357:23256409] WARN: EDirectoryNotFoundException: The specified path was not found
> [/Users/administrator/Library/MobileDevice/Provisioning Profiles]
> 2022-05-30 20:02:20.801 Mosco[84357:23256409] WARN: In: Ioutils.TDirectory.InternalCheckDirPathParam(String, Boolean) + 264
> 2022-05-30 20:02:20.801 Mosco[84357:23256409] WARN: Call stack:
> 2022-05-30 20:02:20.801 Mosco[84357:23256409] WARN: Mosco                     $0000000110508E88 Dw.Exceptions.Posix.TPosixDebug.GlobalGetExceptionStackInfo(TExceptionRecord*) + 136
> 2022-05-30 20:02:20.801 Mosco[84357:23256409] WARN: Mosco                     $000000010FCC5F51 Sysutils.Exception.RaisingException(TExceptionRecord*) + 65
> 2022-05-30 20:02:20.801 Mosco[84357:23256409] WARN: Mosco                     $000000010FCF392B Sysutils.RaiseExceptObject(TExceptionRecord*) + 59
> 2022-05-30 20:02:20.801 Mosco[84357:23256409] WARN: Mosco                     $000000010FCA6CE5 _RaiseAtExcept(TObject*, Pointer) + 69
> 2022-05-30 20:02:20.801 Mosco[84357:23256409] WARN: Mosco                     $000000010FC9F3E7 _RaiseAgain() + 87
> 2022-05-30 20:02:20.801 Mosco[84357:23256409] WARN: Mosco                     $0000000110382CB9 Fmx.Forms.TApplication.CreateForm(Classes.TComponentClass, Pointer) + 345
> 2022-05-30 20:02:20.801 Mosco[84357:23256409] WARN: Mosco                     $0000000110382A6D Fmx.Forms.TApplication.RealCreateForms() + 301
> 2022-05-30 20:02:20.801 Mosco[84357:23256409] WARN: Mosco                     $000000011031888F Fmx.Platform.Mac.TPlatformCocoa.Run() + 47
> 2022-05-30 20:02:20.801 Mosco[84357:23256409] WARN: Mosco                     $000000011038379C Fmx.Forms.TApplication.Run() + 108
> 2022-05-30 20:02:20.801 Mosco[84357:23256409] WARN: Mosco                     $000000011060CFB7 main + 167
> 2022-05-30 20:02:20.801 Mosco[84357:23256409] WARN:                           $000000011A93851E
> 2022-05-30 20:02:20.801 Mosco[84357:23256409] DEBUG: Exception - EDirectoryNotFoundException: The specified path was not found
> [/Users/administrator/Library/MobileDevice/Provisioning Profiles]
> Runtime error 217 at 0000000110392AF4
> objc[84357]: objc_disposeClassPair: class 'FMXWindow' still has subclasses, including 'NSKVONotifying_FMXWindow'!
> objc[84357]: objc_disposeClassPair: class 'FMXWindow' still has subclasses, including 'NSKVONotifying_FMXWindow'!
> administrators-Mac-mini:~ administrator$ 
> administrators-Mac-mini:~ administrator$ 
>

**Comment by birbilis** [comment]
probably the issue is:
2022-05-30 20:02:20.801 Mosco[84357:23256409] WARN: EDirectoryNotFoundException: The specified path was not found
[/Users/administrator/Library/MobileDevice/Provisioning Profiles]

do I need to do some extra steps first?

**Comment by DelphiWorlds** [comment]
> do I need to do some extra steps first?

No, it looks like I need to fix a bug, thanks :-)

**Comment by DelphiWorlds** [comment]
[Mosco.1.2.3.Beta.1.pkg.zip](https://github.com/DelphiWorlds/Mosco/files/8800566/Mosco.1.2.3.Beta.1.pkg.zip)

Can you install this beta please, and let me know if it works for you?

**Comment by birbilis** [comment]
Seems to appear now:
![image](https://user-images.githubusercontent.com/3461504/171114036-8b8c02b0-9e3b-4b9f-9ea4-2fa91042dc0c.png)

btw, noticed that if it's already running and I run it again from command-line it ends up having two icons on the bar. Also it was complaining about not being able to connect to broker:
![image](https://user-images.githubusercontent.com/3461504/171114671-117f7554-ee94-4bb8-ab7f-89a249d62ea0.png)

if I close both and run it say from command-line only this time, it says it connected to broker etc. and eventually writes the IP address, so I guess the fix worked (I see no warnings or errors)

**Comment by DelphiWorlds** [comment]
Yeah, it's not a "single instance" app, yet.. although running it from the /Applications folder it should not run a second instance

**Comment by birbilis** [comment]
Probably there's some glitch there, didn't try running though twice from terminal or twice from installed app icon, tried once of each way to get the two instances. Not sure if it could somehow query the Mac menu to see it's already on it (unless there's some other better mechanism - I'd avoid creating lock files in case they remain after the app crashes / is terminated forcefully by the user or the machine has power failure etc.)

**Comment by birbilis** [comment]
I just notarized fine with this version

Only issue I had is the first time it took me some time to enter the correct pwd to access the keychain which probably caused some timeout internally since it did notarize, but then failed on the ticket stappling step (the base64 encoded ticket wasn't found). Maybe that is an Apple glitch though, not Mosco's

> 2022/05/31 13:57:14.970 Notarization complete!
> 2022/05/31 13:57:14.971 Executing: /usr/bin/xcrun stapler staple "/Users/administrator/PAServer/scratch-dir/SomeSystem/READCOM_App.app"
> 2022/05/31 13:57:16.201 Staple ticket failed with exit code: 65 - Processing: /Users/administrator/PAServer/scratch-dir/SomeSystem/READCOM_App.app
> CloudKit query for READCOM_App.app (2/093........a60) failed due to "Record not found".
> Could not find base64 encoded ticket in response for 2/093........a60
> The staple and validate action failed! Error 65.

(note I placed the ........ and the SomeSystem above)

**Comment by birbilis** [comment]
this same thing with the staple failed also just occured when I typed in multiple times wrong password and eventually correct one at installer creation (notarized + staple ticket options).

attaching the timings of the commands in case it helps:
![image](https://user-images.githubusercontent.com/3461504/171165080-b8942054-a888-46ce-a60a-980832afd1e8.png)

**Comment by birbilis** [comment]
Actually I find that I can notarize installers but not staple ticket on them, not sure why. Shows this same error as above (even though I told it to always allow access to the keystore so that I don't type the password again and again [it was either failing or asking multiple times for access, not sure but kept on showing the password popup several times]).

I can notarized AND staple apps though fine (apart from this issue occuring once for app notarization at my first try)

Another thing that's not clear to me is if I should make notarized installers for notarized .app or if this process notarizes the .app, then notarizes the installer for it (or if it's not needed security-wise to have notarized .app if you have notarized installer [doesn't it give any extra post-install tampering protection?])

**Comment by DelphiWorlds** [comment]
Can you open another issue for the notarization failure? Thanks
