### ISSUE TITLE
Should allow to refresh list of certificates

### ISSUE THREAD

**Issue by birbilis** [DelphiWorlds/Mosco#7]
I was trying to create an installer and picking option to notarize I noticed I hadn't gotten an deverloper Id installer certificate

could have a small ? button there to point to this article: https://delphiworlds.com/2019/07/notarizing-your-macos-64-bit-apps-built-with-delphi/

but most importantly should have a refresh button (or at least do a refresh when I untick and tick back again the "notarize installer") to query for certificate for the installer

similar maybe at other forms that query for certificates have a refresh button in case the user added more certs in the mean time

currently I had to close the create and installer form and open it again (luckily it remembered the fields [guess cause I hadn't closed the Mosco app])

**Comment by DelphiWorlds** [comment]
I agree there should be a refresh option for the certs/profiles. It's now on the todo list

**Comment by DelphiWorlds** [comment]
Added to version 1.3.0
